<div class="space-y-6">
    @if (session()->has('success'))
        <div class="rounded-xl border border-emerald-200 bg-emerald-50 px-4 py-3 text-sm font-semibold text-emerald-800"><i class="fas fa-circle-check mr-2"></i>{{ session('success') }}</div>
    @endif

    <section class="overflow-hidden rounded-3xl bg-gradient-to-br from-sky-950 via-sky-900 to-violet-900 text-white shadow-xl">
        <div class="grid gap-8 p-6 sm:p-8 lg:grid-cols-[1fr_auto] lg:items-center">
            <div><p class="text-xs font-bold uppercase tracking-[0.2em] text-amber-300">Student life</p><h1 class="mt-3 text-3xl font-black sm:text-4xl">Clubs & Activities</h1><p class="mt-4 max-w-3xl leading-7 text-sky-100">Discover interests, follow club activities and stay connected with the instructors and students who make each club active.</p></div>
            @if($canManageAll)<button wire:click="createClub" class="rounded-xl bg-amber-400 px-5 py-3 font-black text-sky-950 hover:bg-amber-300"><i class="fas fa-plus mr-2"></i>Create club</button>@endif
        </div>
    </section>

    @if($children->isNotEmpty())
        <section class="rounded-2xl border border-violet-200 bg-violet-50 p-5"><p class="text-xs font-bold uppercase tracking-widest text-violet-700">Your wards</p><div class="mt-3 flex flex-wrap gap-2">@foreach($children as $child)<span class="rounded-full bg-white px-4 py-2 text-sm font-bold text-violet-900 shadow-sm"><i class="fas fa-child-reaching mr-2 text-violet-500"></i>{{ $child->name }}</span>@endforeach</div><p class="mt-3 text-sm text-violet-800">Only clubs joined by your wards are shown below.</p></section>
    @endif

    @if($showClubForm && $canManageAll)
        <section class="rounded-2xl border border-sky-200 bg-white p-6 shadow-sm">
            <div class="flex items-start justify-between"><div><p class="text-xs font-bold uppercase tracking-widest text-sky-700">Club setup</p><h2 class="mt-1 text-2xl font-black">{{ $editingClubId ? 'Edit club' : 'Create a new club' }}</h2></div><button wire:click="cancelClubForm" class="text-slate-400 hover:text-slate-700" aria-label="Close form"><i class="fas fa-times"></i></button></div>
            <form wire:submit="saveClub" class="mt-6 grid gap-4 md:grid-cols-2">
                <div><label class="mb-1 block text-sm font-bold">Club name</label><input wire:model="name" class="w-full rounded-xl border-slate-300" placeholder="e.g. Young Authors Club">@error('name')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</div>
                <div><label class="mb-1 block text-sm font-bold">Category</label><input wire:model="category" class="w-full rounded-xl border-slate-300" placeholder="Creative, Sports, STEM..."></div>
                <div class="md:col-span-2"><label class="mb-1 block text-sm font-bold">Description</label><textarea wire:model="description" rows="4" class="w-full rounded-xl border-slate-300" placeholder="What students will explore and do in this club"></textarea>@error('description')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror</div>
                <div><label class="mb-1 block text-sm font-bold">Meeting day</label><select wire:model="meetingDay" class="w-full rounded-xl border-slate-300"><option value="">Not fixed</option>@foreach(['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday'] as $day)<option>{{ $day }}</option>@endforeach</select></div>
                <div><label class="mb-1 block text-sm font-bold">Meeting time</label><input type="time" wire:model="meetingTime" class="w-full rounded-xl border-slate-300"></div>
                <div><label class="mb-1 block text-sm font-bold">Meeting location</label><input wire:model="meetingLocation" class="w-full rounded-xl border-slate-300" placeholder="Optional"></div>
                <div><label class="mb-1 block text-sm font-bold">Capacity</label><input type="number" min="1" wire:model="capacity" class="w-full rounded-xl border-slate-300" placeholder="Leave empty for no limit"></div>
                <div><label class="mb-1 block text-sm font-bold">Colour</label><select wire:model="colour" class="w-full rounded-xl border-slate-300">@foreach(['sky'=>'Sky blue','violet'=>'Violet','emerald'=>'Emerald','amber'=>'Amber','rose'=>'Rose','indigo'=>'Indigo'] as $value=>$label)<option value="{{ $value }}">{{ $label }}</option>@endforeach</select></div>
                <label class="flex items-center gap-3 self-end rounded-xl bg-slate-50 px-4 py-3 text-sm font-bold"><input type="checkbox" wire:model="isActive" class="rounded border-slate-300 text-sky-700">Open for student participation</label>
                <div class="md:col-span-2 flex justify-end gap-3 border-t border-slate-200 pt-4"><button type="button" wire:click="cancelClubForm" class="rounded-xl border border-slate-300 px-5 py-2.5 font-bold">Cancel</button><button type="submit" class="rounded-xl bg-sky-700 px-5 py-2.5 font-bold text-white hover:bg-sky-800">Save club</button></div>
            </form>
        </section>
    @endif

    <div class="grid gap-6 xl:grid-cols-[340px_1fr]">
        <aside class="space-y-4">
            <input type="search" wire:model.live.debounce.300ms="search" class="w-full rounded-xl border-slate-300" placeholder="Search clubs">
            <div class="space-y-3">
                @forelse($clubs as $club)
                    @php($active = $selectedClub?->id === $club->id)
                    <button wire:click="selectClub({{ $club->id }})" class="w-full rounded-2xl border p-4 text-left transition {{ $active ? 'border-sky-400 bg-sky-50 shadow-md' : 'border-slate-200 bg-white hover:border-sky-200 hover:shadow-sm' }}">
                        <div class="flex items-start justify-between gap-3"><div><p class="text-xs font-bold uppercase tracking-widest text-{{ $club->colour }}-700">{{ $club->category ?: 'School club' }}</p><h2 class="mt-1 font-black text-slate-950">{{ $club->name }}</h2></div><span class="h-3 w-3 shrink-0 rounded-full bg-{{ $club->colour }}-500"></span></div>
                        <div class="mt-3 flex items-center justify-between text-xs text-slate-500"><span><i class="fas fa-user-group mr-1"></i>{{ $club->active_members_count }} member{{ $club->active_members_count === 1 ? '' : 's' }}</span><span class="font-bold {{ $club->is_active ? 'text-emerald-700' : 'text-slate-500' }}">{{ $club->is_active ? 'Active' : 'Closed' }}</span></div>
                    </button>
                @empty
                    <div class="rounded-2xl border border-dashed border-slate-300 bg-white p-7 text-center"><i class="fas fa-people-group text-3xl text-slate-300"></i><p class="mt-3 font-bold text-slate-700">No clubs to show yet</p><p class="mt-1 text-sm text-slate-500">{{ $canManageAll ? 'Create the first club to get started.' : 'Clubs will appear here when available to you.' }}</p></div>
                @endforelse
            </div>
        </aside>

        @if($selectedClub)
            <div class="space-y-6">
                @php($colourClasses = ['sky'=>'from-sky-800 to-cyan-700','violet'=>'from-violet-800 to-indigo-700','emerald'=>'from-emerald-800 to-teal-700','amber'=>'from-amber-700 to-orange-600','rose'=>'from-rose-800 to-pink-700','indigo'=>'from-indigo-800 to-blue-700'])
                <section class="overflow-hidden rounded-3xl bg-gradient-to-br {{ $colourClasses[$selectedClub->colour] ?? $colourClasses['sky'] }} text-white shadow-lg">
                    <div class="p-6 sm:p-8"><div class="flex flex-col gap-5 sm:flex-row sm:items-start sm:justify-between"><div><p class="text-xs font-bold uppercase tracking-[0.2em] text-white/70">{{ $selectedClub->category ?: 'School club' }}</p><h2 class="mt-2 text-3xl font-black">{{ $selectedClub->name }}</h2><p class="mt-4 max-w-3xl leading-7 text-white/85">{{ $selectedClub->description }}</p></div>@if($canManageAll)<div class="flex gap-2"><button wire:click="editClub({{ $selectedClub->id }})" class="rounded-xl bg-white/15 px-4 py-2 text-sm font-bold hover:bg-white/25"><i class="fas fa-pen mr-2"></i>Edit</button><button wire:click="deleteClub({{ $selectedClub->id }})" wire:confirm="Delete this club, its memberships, instructors and activities?" class="rounded-xl bg-red-950/30 px-4 py-2 text-sm font-bold hover:bg-red-950/50"><i class="fas fa-trash mr-2"></i>Delete</button></div>@endif</div>
                        <div class="mt-6 flex flex-wrap gap-3 text-sm"><span class="rounded-full bg-white/15 px-4 py-2"><i class="fas fa-calendar-day mr-2"></i>{{ $selectedClub->meeting_day ?: 'Flexible day' }}{{ $selectedClub->meeting_time ? ' · '.date('g:i A', strtotime($selectedClub->meeting_time)) : '' }}</span>@if($selectedClub->meeting_location)<span class="rounded-full bg-white/15 px-4 py-2"><i class="fas fa-location-dot mr-2"></i>{{ $selectedClub->meeting_location }}</span>@endif<span class="rounded-full bg-white/15 px-4 py-2"><i class="fas fa-users mr-2"></i>{{ $selectedClub->members->count() }} active</span></div>
                        @if(auth()->user()->hasRole('student'))<div class="mt-6">@if($isJoined)<button wire:click="leaveClub({{ $selectedClub->id }})" wire:confirm="Leave {{ $selectedClub->name }}?" class="rounded-xl border border-white/40 px-5 py-2.5 font-bold hover:bg-white/10">Leave club</button>@elseif($selectedClub->is_active)<button wire:click="joinClub({{ $selectedClub->id }})" class="rounded-xl bg-amber-300 px-5 py-2.5 font-black text-slate-950 hover:bg-amber-200">Join this club</button>@endif</div>@endif
                    </div>
                </section>

                <div class="grid gap-6 lg:grid-cols-2">
                    <section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm">
                        <div class="flex items-center justify-between"><div><p class="text-xs font-bold uppercase tracking-widest text-violet-700">Guidance</p><h3 class="mt-1 text-xl font-black">Club instructors</h3></div><span class="rounded-full bg-violet-100 px-3 py-1 text-xs font-bold text-violet-800">{{ $selectedClub->instructors->count() }}</span></div>
                        <div class="mt-5 space-y-3">@forelse($selectedClub->instructors as $teacher)<div class="flex items-center justify-between rounded-xl bg-slate-50 p-3"><div class="flex items-center gap-3"><img src="{{ $teacher->profile_photo_url }}" alt="" class="h-10 w-10 rounded-full object-cover"><div><p class="font-bold">{{ $teacher->name }}</p><p class="text-xs text-slate-500">{{ $teacher->pivot->is_lead ? 'Lead instructor' : 'Instructor' }}</p></div></div>@if($canManageAll)<button wire:click="removeInstructor({{ $teacher->id }})" wire:confirm="Remove this instructor?" class="text-red-600" aria-label="Remove instructor"><i class="fas fa-times"></i></button>@endif</div>@empty<p class="rounded-xl bg-amber-50 p-4 text-sm text-amber-800">No instructor has been assigned yet.</p>@endforelse</div>
                        @if($canManageAll)<div class="mt-4 flex gap-2"><select wire:model="selectedInstructorId" class="min-w-0 flex-1 rounded-xl border-slate-300 text-sm"><option value="">Choose a teacher</option>@foreach($teachers as $teacher)<option value="{{ $teacher->id }}">{{ $teacher->name }}</option>@endforeach</select><button wire:click="addInstructor" class="rounded-xl bg-violet-700 px-4 text-sm font-bold text-white">Assign</button></div>@error('selectedInstructorId')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror@endif
                    </section>

                    @if($canManageAll || auth()->user()->hasRole('teacher') || auth()->user()->hasRole('parent'))
                        <section class="rounded-2xl border border-slate-200 bg-white p-6 shadow-sm"><div class="flex items-center justify-between"><div><p class="text-xs font-bold uppercase tracking-widest text-emerald-700">Participation</p><h3 class="mt-1 text-xl font-black">{{ auth()->user()->hasRole('parent') ? 'Your wards in this club' : 'Student members' }}</h3></div><span class="rounded-full bg-emerald-100 px-3 py-1 text-xs font-bold text-emerald-800">{{ $selectedClub->members->count() }}</span></div><div class="mt-5 max-h-64 space-y-2 overflow-y-auto">@forelse($selectedClub->members as $student)<div class="flex items-center justify-between rounded-xl bg-slate-50 p-3"><div><p class="font-bold">{{ $student->name }}</p><p class="text-xs text-slate-500">{{ $student->studentRecord?->baseClass?->name ?: 'Student' }} · Joined {{ \Carbon\Carbon::parse($student->pivot->joined_on)->format('j M Y') }}</p></div>@if($canManageAll)<button wire:click="removeStudent({{ $student->id }})" wire:confirm="Remove this student from the club?" class="text-red-600" aria-label="Remove student"><i class="fas fa-times"></i></button>@endif</div>@empty<p class="rounded-xl bg-slate-50 p-4 text-sm text-slate-500">No active student memberships yet.</p>@endforelse</div>@if($canManageAll)<div class="mt-4 flex gap-2"><select wire:model="selectedStudentId" class="min-w-0 flex-1 rounded-xl border-slate-300 text-sm"><option value="">Choose a student</option>@foreach($students as $student)<option value="{{ $student->id }}">{{ $student->name }}</option>@endforeach</select><button wire:click="addStudent" class="rounded-xl bg-emerald-700 px-4 text-sm font-bold text-white">Add</button></div>@error('selectedStudentId')<p class="mt-1 text-xs text-red-600">{{ $message }}</p>@enderror@endif</section>
                    @endif
                </div>

                <section class="rounded-2xl border border-slate-200 bg-white shadow-sm">
                    <div class="flex flex-col gap-3 border-b border-slate-200 p-6 sm:flex-row sm:items-center sm:justify-between"><div><p class="text-xs font-bold uppercase tracking-widest text-sky-700">Club calendar</p><h3 class="mt-1 text-xl font-black">Activities</h3><p class="mt-1 text-sm text-slate-500">Meetings, projects, practices and other club events.</p></div>@if($canManageSelected)<button wire:click="createActivity" class="rounded-xl bg-sky-700 px-4 py-2.5 text-sm font-bold text-white hover:bg-sky-800"><i class="fas fa-plus mr-2"></i>Add activity</button>@endif</div>
                    @if($showActivityForm && $canManageSelected)<form wire:submit="saveActivity" class="grid gap-4 border-b border-sky-100 bg-sky-50 p-6 md:grid-cols-2"><div class="md:col-span-2"><label class="mb-1 block text-sm font-bold">Activity title</label><input wire:model="activityTitle" class="w-full rounded-xl border-slate-300">@error('activityTitle')<p class="text-xs text-red-600">{{ $message }}</p>@enderror</div><div><label class="mb-1 block text-sm font-bold">Starts</label><input type="datetime-local" wire:model="activityStartsAt" class="w-full rounded-xl border-slate-300">@error('activityStartsAt')<p class="text-xs text-red-600">{{ $message }}</p>@enderror</div><div><label class="mb-1 block text-sm font-bold">Ends</label><input type="datetime-local" wire:model="activityEndsAt" class="w-full rounded-xl border-slate-300"></div><div><label class="mb-1 block text-sm font-bold">Location</label><input wire:model="activityLocation" class="w-full rounded-xl border-slate-300"></div><div><label class="mb-1 block text-sm font-bold">Status</label><select wire:model="activityStatus" class="w-full rounded-xl border-slate-300"><option value="scheduled">Scheduled</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select></div><div class="md:col-span-2"><label class="mb-1 block text-sm font-bold">Details</label><textarea wire:model="activityDescription" rows="3" class="w-full rounded-xl border-slate-300"></textarea></div><div class="md:col-span-2 flex justify-between"><div>@if($editingActivityId)<button type="button" wire:click="deleteActivity({{ $editingActivityId }})" wire:confirm="Delete this activity?" class="rounded-xl border border-red-200 px-4 py-2 text-sm font-bold text-red-700">Delete</button>@endif</div><div class="flex gap-2"><button type="button" wire:click="cancelActivityForm" class="rounded-xl border border-slate-300 px-4 py-2 text-sm font-bold">Cancel</button><button type="submit" class="rounded-xl bg-sky-700 px-5 py-2 text-sm font-bold text-white">Save activity</button></div></div></form>@endif
                    <div class="divide-y divide-slate-100">@if(!$canViewActivities)<div class="p-8 text-center"><i class="fas fa-lock text-2xl text-slate-300"></i><p class="mt-3 font-bold">Join this club to see its activities</p><p class="mt-1 text-sm text-slate-500">Activity details are available to members, parents, instructors and administrators.</p></div>@else @forelse($selectedClub->activities as $activity)<article class="flex flex-col gap-4 p-5 sm:flex-row sm:items-start"><div class="flex h-14 w-14 shrink-0 flex-col items-center justify-center rounded-2xl bg-sky-100 text-sky-900"><span class="text-[10px] font-bold uppercase">{{ $activity->starts_at->format('M') }}</span><span class="text-xl font-black">{{ $activity->starts_at->format('d') }}</span></div><div class="min-w-0 flex-1"><div class="flex flex-wrap items-center gap-2"><h4 class="text-lg font-black">{{ $activity->title }}</h4><span class="rounded-full px-2.5 py-1 text-[10px] font-bold uppercase {{ $activity->status === 'cancelled' ? 'bg-red-100 text-red-700' : ($activity->status === 'completed' ? 'bg-emerald-100 text-emerald-700' : 'bg-amber-100 text-amber-800') }}">{{ $activity->status }}</span></div><p class="mt-1 text-sm font-semibold text-slate-600">{{ $activity->starts_at->format('l, j F Y · g:i A') }}@if($activity->location) · {{ $activity->location }}@endif</p>@if($activity->description)<p class="mt-3 leading-7 text-slate-600">{{ $activity->description }}</p>@endif</div>@if($canManageSelected)<button wire:click="editActivity({{ $activity->id }})" class="rounded-xl border border-slate-200 px-3 py-2 text-sm font-bold text-slate-600 hover:bg-slate-50"><i class="fas fa-pen"></i></button>@endif</article>@empty<div class="p-8 text-center text-slate-500"><i class="fas fa-calendar-plus text-3xl text-slate-300"></i><p class="mt-3 font-bold text-slate-700">No activities published yet</p><p class="mt-1 text-sm">Club activities will appear here when scheduled.</p></div>@endforelse @endif</div>
                </section>
            </div>
        @endif
    </div>
</div>
